import React from 'react';
import { Cpu, CheckCircle2, Terminal, Lightbulb, Compass } from 'lucide-react';

export default function AIDigest({ summaryData }) {
  if (!summaryData) return null;

  return (
    <div>
      <div style={{ marginBottom: '24px' }}>
        <h2 style={{ fontSize: '22px', fontWeight: 800, marginBottom: '6px' }}>
          AI Intelligence & Ecosystem Digest
        </h2>
        <p style={{ color: 'var(--text-muted)', fontSize: '14px' }}>
          Autonomous synthesis generated by analyzing cross-source discourse patterns, cluster velocity, and corporate engineering job boards.
        </p>
      </div>

      <div className="glass-card" style={{ padding: '28px', marginBottom: '24px', borderColor: 'rgba(6,182,212,0.3)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '12px' }}>
          <span className="pulse-dot"></span>
          <span style={{ fontSize: '12px', color: '#06b6d4', fontFamily: 'var(--font-mono)', fontWeight: 600 }}>
            CROSS-SOURCE SYNTHESIS
          </span>
        </div>

        <h3 style={{ fontSize: '22px', fontWeight: 800, marginBottom: '14px', color: 'var(--text-main)' }}>
          {summaryData.headline}
        </h3>

        <p style={{ color: '#cbd5e1', fontSize: '15px', lineHeight: '1.7' }}>
          {summaryData.executive_summary}
        </p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '20px' }}>
        {/* Key Breakthroughs */}
        <div className="glass-card" style={{ padding: '24px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px' }}>
            <div style={{ padding: '8px', borderRadius: '8px', background: 'rgba(6,182,212,0.15)', color: '#06b6d4' }}>
              <CheckCircle2 size={18} />
            </div>
            <h4 style={{ fontSize: '16px', fontWeight: 700 }}>Key Breakthroughs</h4>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {summaryData.key_breakthroughs.map((item, idx) => (
              <div key={idx} style={{ display: 'flex', gap: '10px', fontSize: '13px', color: '#cbd5e1', lineHeight: '1.5' }}>
                <span style={{ color: '#06b6d4', fontWeight: 700 }}>•</span>
                <span>{item}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Emerging Developer Tools */}
        <div className="glass-card" style={{ padding: '24px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px' }}>
            <div style={{ padding: '8px', borderRadius: '8px', background: 'rgba(139,92,246,0.15)', color: '#8b5cf6' }}>
              <Terminal size={18} />
            </div>
            <h4 style={{ fontSize: '16px', fontWeight: 700 }}>Developer Tooling Shifts</h4>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {summaryData.emerging_developer_tools.map((item, idx) => (
              <div key={idx} style={{ display: 'flex', gap: '10px', fontSize: '13px', color: '#cbd5e1', lineHeight: '1.5' }}>
                <span style={{ color: '#8b5cf6', fontWeight: 700 }}>•</span>
                <span>{item}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Market Signals */}
        <div className="glass-card" style={{ padding: '24px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px' }}>
            <div style={{ padding: '8px', borderRadius: '8px', background: 'rgba(16,185,129,0.15)', color: '#10b981' }}>
              <Compass size={18} />
            </div>
            <h4 style={{ fontSize: '16px', fontWeight: 700 }}>Market Hiring Signals</h4>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {summaryData.market_signals.map((item, idx) => (
              <div key={idx} style={{ display: 'flex', gap: '10px', fontSize: '13px', color: '#cbd5e1', lineHeight: '1.5' }}>
                <span style={{ color: '#10b981', fontWeight: 700 }}>•</span>
                <span>{item}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
